name: NuGet Publish

on:
  push:
    tags:
      - v*

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x
    - name: Build and Test
      run: dotnet test --verbosity normal
    - name: Set version
      id: set_version
      run: |
        VERSION_TAG=${{ github.ref_name }}
        VERSION=${VERSION_TAG//v/}
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "version_tag=$VERSION_TAG" >> $GITHUB_OUTPUT
    - name: Build release
      run: dotnet build -c Release /p:Version=${{ steps.set_version.outputs.version }}
    - name: Publish GitHub
      run: |
        dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUBTOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/DrEsteban/index.json"
        dotnet nuget push --skip-duplicate --api-key ${{ secrets.GITHUBTOKEN }} ./**/Release/*.nupkg --source github
    - name: Publish NuGet
      run: dotnet nuget push --skip-duplicate --api-key ${{ secrets.NUGETTOKEN }} ./**/Release/*.nupkg --source https://api.nuget.org/v3/index.json
    - name: Zip artifacts
      run: |
        mkdir -p ./zip
        zip -r ./zip/DotNetDefer.zip ./DotNetDefer/bin/Release
        zip -r ./zip/DotNetDefer.Legacy.zip ./DotNetDefer.Legacy/bin/Release
    - name: Create GitHub Release
      uses: ncipollo/release-action@v1.14.0
      with:
        artifacts: ./DotNetDefer/bin/Release/*.nupkg,./DotNetDefer.Legacy/bin/Release/*.nupkg,./zip/*.zip
        token: ${{ secrets.GITHUBTOKEN }}
        tag: ${{ steps.set_version.outputs.version_tag }}
        commit: ${{ github.sha }}
        generateReleaseNotes: true
        prerelease: false
        allowUpdates: true
